# Fall damage is canceled until the player reaches a block
safeX: 0 # The integer x location a player is teleported to
safeY: 255 # The integer y location. Do not let the player fall for 15 seconds or the damage will apply.
safeZ: 0 # The integer z location
safeWorld: "world" # Generally the worlds are named: "world", "world_nether", and "world_the_end"
teleportToRandomPos: true # Ignores safe X, Y, and Z and will use a random position anywhere in the safeWorld instead, spawning the player 500 blocks up
randomTeleportBoundsFromCenter: 10000 # From 0,0 it will find a place +- this many blocks away to teleport to
useBlindingEffect: false # Blinds the user for a short amount of time to make the teleport transition smoother
blindingEffectDuration: 40 # in ticks, 20 per second
