name: VoidEscape
version: '${project.version}'
main: me.grovre.voidescape.VoidEscape
api-version: 1.18
authors: [ PoptartFromPluto ]
description: Teleports players out of the void
website: https://github.com/grovre
